"""initial schema

Revision ID: b49b366fa7a1
Revises: 
Create Date: 2026-10-06 03:18:02.128753
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b49b366fa7a1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('use_case', sa.String(length=48), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('was_cached', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage_ledger'))
    )
    op.create_index('ix_ai_usage_model_day', 'ai_usage_ledger', ['model', 'occurred_on'], unique=False)
    op.create_index('ix_ai_usage_use_case_day', 'ai_usage_ledger', ['use_case', 'occurred_on'], unique=False)
    op.create_index('ix_ai_usage_user_day', 'ai_usage_ledger', ['user_id', 'occurred_on'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=48), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_action_time', 'audit_log', ['action', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index('ix_audit_subject', 'audit_log', ['subject_type', 'subject_id', 'occurred_at'], unique=False)
    op.create_table('conversation_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('flow', sa.String(length=40), nullable=False),
    sa.Column('step', sa.String(length=40), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('dropouts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_metrics'))
    )
    op.create_index('uq_conversation_metrics_bucket', 'conversation_metrics', ['occurred_on', 'flow', 'step'], unique=True)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('flow', sa.String(length=40), nullable=False),
    sa.Column('step', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('assigned_property_id', sa.UUID(), nullable=True),
    sa.Column('last_step_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_sessions'))
    )
    op.create_index(op.f('ix_conversation_sessions_phone_e164'), 'conversation_sessions', ['phone_e164'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_user_id'), 'conversation_sessions', ['user_id'], unique=False)
    op.create_index('ix_session_flow_step', 'conversation_sessions', ['flow', 'step', 'status'], unique=False)
    op.create_index('ix_session_phone_active', 'conversation_sessions', ['phone_e164', 'status', 'updated_at'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('intent', sa.String(length=48), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('used_llm', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_turns'))
    )
    op.create_index(op.f('ix_conversation_turns_session_id'), 'conversation_turns', ['session_id'], unique=False)
    op.create_index('ix_turn_session_time', 'conversation_turns', ['session_id', 'created_at'], unique=False)
    op.create_table('fraud_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=24), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fraud_signals')),
    sa.UniqueConstraint('profile_id', 'reason', 'detected_at', name='uq_fraud_signal_profile_reason_time')
    )
    op.create_index('ix_fraud_signal_active', 'fraud_signals', ['subject', 'subject_id', 'active', 'reason'], unique=False)
    op.create_index('ix_fraud_signal_detected', 'fraud_signals', ['detected_at'], unique=False)
    op.create_index(op.f('ix_fraud_signals_profile_id'), 'fraud_signals', ['profile_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=180), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('scope', 'key', name='uq_idempotency_scope_key')
    )
    op.create_index('ix_idempotency_created', 'idempotency_keys', ['created_at'], unique=False)
    op.create_table('inbound_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_message_id', sa.String(length=180), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('conversation_ref', sa.String(length=96), nullable=False),
    sa.Column('sender_phone', sa.String(length=20), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('message_kind', sa.String(length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_object_key', sa.String(length=255), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('provider_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_messages'))
    )
    op.create_index('ix_inbound_conversation_time', 'inbound_messages', ['conversation_ref', 'provider_timestamp'], unique=False)
    op.create_index(op.f('ix_inbound_messages_sender_phone'), 'inbound_messages', ['sender_phone'], unique=False)
    op.create_index(op.f('ix_inbound_messages_session_id'), 'inbound_messages', ['session_id'], unique=False)
    op.create_index('ix_inbound_unprocessed', 'inbound_messages', ['received_at'], unique=False, postgresql_where=sa.text('processed IS false'))
    op.create_index('uq_inbound_external_message', 'inbound_messages', ['provider', 'external_message_id'], unique=True)
    op.create_table('landlord_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('verification_status', sa.String(length=24), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('successful_rentals', sa.Integer(), nullable=False),
    sa.Column('active_property_count', sa.Integer(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_landlord_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_landlord_profiles_user_id'))
    )
    op.create_index('ix_landlord_status', 'landlord_profiles', ['verification_status', 'created_at'], unique=False)
    op.create_table('media_hashes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('landlord_id', sa.UUID(), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=32), nullable=False),
    sa.Column('hamming_band', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_hashes'))
    )
    op.create_index('ix_media_hash_lookup', 'media_hashes', ['perceptual_hash', 'landlord_id'], unique=False)
    op.create_index(op.f('ix_media_hashes_landlord_id'), 'media_hashes', ['landlord_id'], unique=False)
    op.create_index(op.f('ix_media_hashes_perceptual_hash'), 'media_hashes', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_media_hashes_property_id'), 'media_hashes', ['property_id'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=180), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('conversation_ref', sa.String(length=96), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('message_kind', sa.String(length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_object_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_message_id', sa.String(length=180), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_messages')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_outbound_messages_idempotency_key'))
    )
    op.create_index(op.f('ix_outbound_messages_recipient_phone'), 'outbound_messages', ['recipient_phone'], unique=False)
    op.create_index(op.f('ix_outbound_messages_session_id'), 'outbound_messages', ['session_id'], unique=False)
    op.create_index('ix_outbound_pending', 'outbound_messages', ['queued_at'], unique=False, postgresql_where=sa.text("status IN ('QUEUED', 'SENT')"))
    op.create_index('ix_outbound_status_time', 'outbound_messages', ['status', 'queued_at'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=96), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('causation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index(op.f('ix_outbox_events_correlation_id'), 'outbox_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_topic'), 'outbox_events', ['topic'], unique=False)
    op.create_index('ix_outbox_unpublished', 'outbox_events', ['occurred_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('payment_callbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=180), nullable=False),
    sa.Column('payload_signature', sa.String(length=128), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_callbacks')),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_payment_callback_provider_event')
    )
    op.create_index('ix_payment_callback_received', 'payment_callbacks', ['received_at'], unique=False)
    op.create_table('phone_verification_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_verification_challenges'))
    )
    op.create_index('ix_phone_challenge_open', 'phone_verification_challenges', ['expires_at'], unique=False, postgresql_where=sa.text('consumed_at IS NULL'))
    op.create_index('ix_phone_challenge_user_purpose', 'phone_verification_challenges', ['user_id', 'purpose', 'created_at'], unique=False)
    op.create_index(op.f('ix_phone_verification_challenges_user_id'), 'phone_verification_challenges', ['user_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('landlord_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.String(length=24), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('neighbourhood', sa.String(length=96), nullable=True),
    sa.Column('address_hint', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('rent_xaf', sa.BigInteger(), nullable=True),
    sa.Column('charges_xaf', sa.BigInteger(), nullable=True),
    sa.Column('public_price_xaf', sa.BigInteger(), nullable=True),
    sa.Column('charging_policy', sa.String(length=16), nullable=False),
    sa.Column('deposit_xaf', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('surface_m2', sa.Integer(), nullable=True),
    sa.Column('minimum_duration_months', sa.Integer(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('landlord_rules', sa.Text(), nullable=True),
    sa.Column('data_quality_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completeness_score', sa.Double(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_availability_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_document', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties'))
    )
    op.create_index('ix_properties_available_from', 'properties', ['available_from'], unique=False, postgresql_where=sa.text("status IN ('AVAILABLE')"))
    op.create_index(op.f('ix_properties_landlord_id'), 'properties', ['landlord_id'], unique=False)
    op.create_index('ix_properties_landlord_status', 'properties', ['landlord_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_properties_public_search', 'properties', ['status', 'city', 'public_price_xaf', 'created_at'], unique=False)
    op.create_index('ix_properties_search_document', 'properties', ['search_document'], unique=False)
    op.create_index('ix_properties_stale_availability', 'properties', ['last_availability_confirmed_at'], unique=False, postgresql_where=sa.text("status IN ('AVAILABLE')"))
    op.create_index('ix_properties_type_status', 'properties', ['property_type', 'status'], unique=False)
    op.create_index('ix_properties_unpublished', 'properties', ['created_at'], unique=False, postgresql_where=sa.text("status IN ('DRAFT')"))
    op.create_table('property_availability_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('landlord_id', sa.UUID(), nullable=False),
    sa.Column('asked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer', sa.String(length=32), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_ask_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_availability_checks'))
    )
    op.create_index('ix_availability_due', 'property_availability_checks', ['next_ask_at', 'answered_at'], unique=False)
    op.create_index(op.f('ix_property_availability_checks_property_id'), 'property_availability_checks', ['property_id'], unique=False)
    op.create_table('property_data_quality_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('issue', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('asked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('landlord_answer', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_data_quality_issues'))
    )
    op.create_index(op.f('ix_property_data_quality_issues_property_id'), 'property_data_quality_issues', ['property_id'], unique=False)
    op.create_index('ix_quality_open_issues', 'property_data_quality_issues', ['property_id', 'issue'], unique=False, postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_table('property_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('perceptual_hash', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('quarantine_reason', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_media')),
    sa.UniqueConstraint('object_key', name=op.f('uq_property_media_object_key'))
    )
    op.create_index('ix_property_media_duplicate', 'property_media', ['perceptual_hash', 'property_id'], unique=False)
    op.create_index('ix_property_media_order', 'property_media', ['property_id', 'position'], unique=False)
    op.create_index(op.f('ix_property_media_perceptual_hash'), 'property_media', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_property_media_property_id'), 'property_media', ['property_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('device_label', sa.String(length=64), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin_session', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_token_user_active', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('ix_reports_open_queue', 'reports', ['status', 'created_at'], unique=False)
    op.create_index('ix_reports_reporter', 'reports', ['reporter_id', 'created_at'], unique=False)
    op.create_index('ix_reports_target', 'reports', ['target_type', 'target_id', 'status'], unique=False)
    op.create_table('risk_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=24), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('recommended_action', sa.String(length=32), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('under_manual_review', sa.Boolean(), nullable=False),
    sa.Column('restricted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_profiles'))
    )
    op.create_index('ix_risk_profile_band', 'risk_profiles', ['risk_band', 'risk_score'], unique=False)
    op.create_index('ix_risk_profile_restricted', 'risk_profiles', ['restricted_until'], unique=False)
    op.create_index('ix_risk_profile_review_queue', 'risk_profiles', ['under_manual_review', 'last_evaluated_at'], unique=False)
    op.create_index('uq_risk_profile_subject', 'risk_profiles', ['subject', 'subject_id'], unique=True)
    op.create_table('service_access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('landlord_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reveal_count', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_access_grants'))
    )
    op.create_index(op.f('ix_service_access_grants_tenant_id'), 'service_access_grants', ['tenant_id'], unique=False)
    op.create_index('uq_grant_active_application', 'service_access_grants', ['application_id'], unique=True, postgresql_where="status = 'ACTIVE'")
    op.create_index('uq_grant_payment', 'service_access_grants', ['payment_id'], unique=True)
    op.create_table('service_fee_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('landlord_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('amount_xaf', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_reference', sa.String(length=180), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_fee_payments'))
    )
    op.create_index('ix_payment_status_time', 'service_fee_payments', ['status', 'created_at'], unique=False)
    op.create_index('ix_payment_tenant_time', 'service_fee_payments', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_service_fee_payments_application_id'), 'service_fee_payments', ['application_id'], unique=False)
    op.create_index(op.f('ix_service_fee_payments_landlord_id'), 'service_fee_payments', ['landlord_id'], unique=False)
    op.create_index('uq_payment_open_application', 'service_fee_payments', ['application_id'], unique=True, postgresql_where="status IN ('CREATED', 'INITIATED', 'PENDING_CONFIRMATION')")
    op.create_index('uq_payment_provider_reference', 'service_fee_payments', ['provider', 'provider_reference'], unique=True, postgresql_where='provider_reference IS NOT NULL')
    op.create_table('trust_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('landlord_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('account_age_days', sa.Integer(), nullable=False),
    sa.Column('successful_rentals', sa.Integer(), nullable=False),
    sa.Column('cancelled_applications', sa.Integer(), nullable=False),
    sa.Column('availability_accuracy', sa.Double(), nullable=False),
    sa.Column('price_accuracy', sa.Double(), nullable=False),
    sa.Column('condition_compliance', sa.Double(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trust_profiles')),
    sa.UniqueConstraint('landlord_id', name=op.f('uq_trust_profiles_landlord_id'))
    )
    op.create_index('ix_trust_score', 'trust_profiles', ['score'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('phone_e164_hash', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone_e164', name=op.f('uq_users_phone_e164')),
    sa.UniqueConstraint('phone_e164_hash', name=op.f('uq_users_phone_e164_hash'))
    )
    op.create_index('ix_users_roles_gin', 'users', ['roles'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_status_created', 'users', ['status', 'created_at'], unique=False)
    op.create_table('verification_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('ocr_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_documents'))
    )
    op.create_index('ix_verification_doc_request', 'verification_documents', ['request_id', 'kind'], unique=False)
    op.create_index(op.f('ix_verification_documents_request_id'), 'verification_documents', ['request_id'], unique=False)
    op.create_table('verification_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('landlord_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('review_mode', sa.String(length=16), nullable=False),
    sa.Column('rejection_reason', sa.String(length=48), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('selfie_object_key', sa.String(length=255), nullable=True),
    sa.Column('selfie_checksum', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_requests'))
    )
    op.create_index('ix_verification_landlord_status', 'verification_requests', ['landlord_id', 'status'], unique=False)
    op.create_index('ix_verification_queue', 'verification_requests', ['status', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_verification_requests_landlord_id'), 'verification_requests', ['landlord_id'], unique=False)
    op.create_index(op.f('ix_verification_requests_user_id'), 'verification_requests', ['user_id'], unique=False)
    op.create_table('webhook_replay_guards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('payload_signature', sa.String(length=128), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_replay_guards')),
    sa.UniqueConstraint('provider', 'payload_signature', name='uq_webhook_replay_provider_signature')
    )
    op.create_index('ix_webhook_replay_received', 'webhook_replay_guards', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_replay_received', table_name='webhook_replay_guards')
    op.drop_table('webhook_replay_guards')
    op.drop_index(op.f('ix_verification_requests_user_id'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_landlord_id'), table_name='verification_requests')
    op.drop_index('ix_verification_queue', table_name='verification_requests')
    op.drop_index('ix_verification_landlord_status', table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_index(op.f('ix_verification_documents_request_id'), table_name='verification_documents')
    op.drop_index('ix_verification_doc_request', table_name='verification_documents')
    op.drop_table('verification_documents')
    op.drop_index('ix_users_status_created', table_name='users')
    op.drop_index('ix_users_roles_gin', table_name='users', postgresql_using='gin')
    op.drop_table('users')
    op.drop_index('ix_trust_score', table_name='trust_profiles')
    op.drop_table('trust_profiles')
    op.drop_index('uq_payment_provider_reference', table_name='service_fee_payments', postgresql_where='provider_reference IS NOT NULL')
    op.drop_index('uq_payment_open_application', table_name='service_fee_payments', postgresql_where="status IN ('CREATED', 'INITIATED', 'PENDING_CONFIRMATION')")
    op.drop_index(op.f('ix_service_fee_payments_landlord_id'), table_name='service_fee_payments')
    op.drop_index(op.f('ix_service_fee_payments_application_id'), table_name='service_fee_payments')
    op.drop_index('ix_payment_tenant_time', table_name='service_fee_payments')
    op.drop_index('ix_payment_status_time', table_name='service_fee_payments')
    op.drop_table('service_fee_payments')
    op.drop_index('uq_grant_payment', table_name='service_access_grants')
    op.drop_index('uq_grant_active_application', table_name='service_access_grants', postgresql_where="status = 'ACTIVE'")
    op.drop_index(op.f('ix_service_access_grants_tenant_id'), table_name='service_access_grants')
    op.drop_table('service_access_grants')
    op.drop_index('uq_risk_profile_subject', table_name='risk_profiles')
    op.drop_index('ix_risk_profile_review_queue', table_name='risk_profiles')
    op.drop_index('ix_risk_profile_restricted', table_name='risk_profiles')
    op.drop_index('ix_risk_profile_band', table_name='risk_profiles')
    op.drop_table('risk_profiles')
    op.drop_index('ix_reports_target', table_name='reports')
    op.drop_index('ix_reports_reporter', table_name='reports')
    op.drop_index('ix_reports_open_queue', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_user_active', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_property_media_property_id'), table_name='property_media')
    op.drop_index(op.f('ix_property_media_perceptual_hash'), table_name='property_media')
    op.drop_index('ix_property_media_order', table_name='property_media')
    op.drop_index('ix_property_media_duplicate', table_name='property_media')
    op.drop_table('property_media')
    op.drop_index('ix_quality_open_issues', table_name='property_data_quality_issues', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_index(op.f('ix_property_data_quality_issues_property_id'), table_name='property_data_quality_issues')
    op.drop_table('property_data_quality_issues')
    op.drop_index(op.f('ix_property_availability_checks_property_id'), table_name='property_availability_checks')
    op.drop_index('ix_availability_due', table_name='property_availability_checks')
    op.drop_table('property_availability_checks')
    op.drop_index('ix_properties_unpublished', table_name='properties', postgresql_where=sa.text("status IN ('DRAFT')"))
    op.drop_index('ix_properties_type_status', table_name='properties')
    op.drop_index('ix_properties_stale_availability', table_name='properties', postgresql_where=sa.text("status IN ('AVAILABLE')"))
    op.drop_index('ix_properties_search_document', table_name='properties')
    op.drop_index('ix_properties_public_search', table_name='properties')
    op.drop_index('ix_properties_landlord_status', table_name='properties')
    op.drop_index(op.f('ix_properties_landlord_id'), table_name='properties')
    op.drop_index('ix_properties_available_from', table_name='properties', postgresql_where=sa.text("status IN ('AVAILABLE')"))
    op.drop_table('properties')
    op.drop_index(op.f('ix_phone_verification_challenges_user_id'), table_name='phone_verification_challenges')
    op.drop_index('ix_phone_challenge_user_purpose', table_name='phone_verification_challenges')
    op.drop_index('ix_phone_challenge_open', table_name='phone_verification_challenges', postgresql_where=sa.text('consumed_at IS NULL'))
    op.drop_table('phone_verification_challenges')
    op.drop_index('ix_payment_callback_received', table_name='payment_callbacks')
    op.drop_table('payment_callbacks')
    op.drop_index('ix_outbox_unpublished', table_name='outbox_events', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_index(op.f('ix_outbox_events_topic'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_correlation_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_outbound_status_time', table_name='outbound_messages')
    op.drop_index('ix_outbound_pending', table_name='outbound_messages', postgresql_where=sa.text("status IN ('QUEUED', 'SENT')"))
    op.drop_index(op.f('ix_outbound_messages_session_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_recipient_phone'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_media_hashes_property_id'), table_name='media_hashes')
    op.drop_index(op.f('ix_media_hashes_perceptual_hash'), table_name='media_hashes')
    op.drop_index(op.f('ix_media_hashes_landlord_id'), table_name='media_hashes')
    op.drop_index('ix_media_hash_lookup', table_name='media_hashes')
    op.drop_table('media_hashes')
    op.drop_index('ix_landlord_status', table_name='landlord_profiles')
    op.drop_table('landlord_profiles')
    op.drop_index('uq_inbound_external_message', table_name='inbound_messages')
    op.drop_index('ix_inbound_unprocessed', table_name='inbound_messages', postgresql_where=sa.text('processed IS false'))
    op.drop_index(op.f('ix_inbound_messages_session_id'), table_name='inbound_messages')
    op.drop_index(op.f('ix_inbound_messages_sender_phone'), table_name='inbound_messages')
    op.drop_index('ix_inbound_conversation_time', table_name='inbound_messages')
    op.drop_table('inbound_messages')
    op.drop_index('ix_idempotency_created', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_fraud_signals_profile_id'), table_name='fraud_signals')
    op.drop_index('ix_fraud_signal_detected', table_name='fraud_signals')
    op.drop_index('ix_fraud_signal_active', table_name='fraud_signals')
    op.drop_table('fraud_signals')
    op.drop_index('ix_turn_session_time', table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_session_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index('ix_session_phone_active', table_name='conversation_sessions')
    op.drop_index('ix_session_flow_step', table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_user_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_phone_e164'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index('uq_conversation_metrics_bucket', table_name='conversation_metrics')
    op.drop_table('conversation_metrics')
    op.drop_index('ix_audit_subject', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index('ix_audit_action_time', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_ai_usage_user_day', table_name='ai_usage_ledger')
    op.drop_index('ix_ai_usage_use_case_day', table_name='ai_usage_ledger')
    op.drop_index('ix_ai_usage_model_day', table_name='ai_usage_ledger')
    op.drop_table('ai_usage_ledger')
    # ### end Alembic commands ###