"""Report endpoints.

Submitting a report is open to any authenticated user; reviewing one is an
analyst action. The report id is generated by the domain, never accepted from
the client, and the reporter is taken from the principal, never from the body.
"""

from __future__ import annotations

import uuid
from typing import Annotated

from fastapi import APIRouter, Depends, Request, status
from pydantic import BaseModel, Field

from loka.bounded_contexts.fraud.application.use_cases.list_reports import (
    ReportListQuery,
)
from loka.bounded_contexts.fraud.application.use_cases.review_report import (
    ReviewReportAction,
    ReviewReportCommand,
)
from loka.bounded_contexts.fraud.application.use_cases.submit_report import (
    SubmitReportCommand,
)
from loka.bounded_contexts.fraud.domain.entities.risk_profile import (
    ReportReason,
    ReportStatus,
)
from loka.interfaces.http.auth import Principal, require_admin, require_principal
from loka.interfaces.http.container import get_container
from loka.shared.domain.clock import SystemClock
from loka.shared.infrastructure.composition import (
    list_reports_use_case,
    review_report_use_case,
    submit_report_use_case,
    unit_of_work,
)

router = APIRouter(prefix="/reports", tags=["reports"])
clock = SystemClock()


class SubmitReportRequest(BaseModel):
    target_type: str = Field(
        pattern="^(PROPERTY|LANDLORD|USER)$",
        description="What is being reported: PROPERTY, LANDLORD or USER.",
    )
    target_id: uuid.UUID
    reason: ReportReason
    description: str = Field(min_length=10, max_length=2000)
    evidence: list[str] = Field(default_factory=list, max_length=8)


class ReviewReportRequest(BaseModel):
    action: ReviewReportAction
    resolution: str | None = None


@router.post("", status_code=status.HTTP_201_CREATED)
async def submit_report(
    body: SubmitReportRequest,
    request: Request,
    principal: Annotated[Principal, Depends(require_principal)],
) -> dict[str, object]:
    database = get_container(request).database
    async with unit_of_work(database) as uow:
        view = await submit_report_use_case(uow).execute(
            SubmitReportCommand(
                reporter_id=principal.user_id,
                target_type=body.target_type,
                target_id=body.target_id,
                reason=body.reason,
                description=body.description,
                evidence=body.evidence,
            ),
            now=clock.now(),
        )
    return view.to_dict()


@router.get("", status_code=status.HTTP_200_OK)
async def list_reports(
    request: Request,
    _: Annotated[Principal, Depends(require_admin)],
    status_filter: ReportStatus | None = None,
    limit: int = 50,
    offset: int = 0,
) -> dict[str, object]:
    database = get_container(request).database
    async with unit_of_work(database) as uow:
        views = await list_reports_use_case(uow).execute(
            ReportListQuery(status=status_filter, limit=limit, offset=offset),
            now=clock.now(),
        )
    return {"items": [view.to_dict() for view in views], "total": len(views)}


@router.post("/{report_id}/review", status_code=status.HTTP_200_OK)
async def review_report(
    report_id: uuid.UUID,
    body: ReviewReportRequest,
    request: Request,
    principal: Annotated[Principal, Depends(require_admin)],
) -> dict[str, object]:
    database = get_container(request).database
    async with unit_of_work(database) as uow:
        view = await review_report_use_case(uow).execute(
            ReviewReportCommand(
                report_id=report_id,
                action=body.action,
                analyst_id=principal.user_id,
                resolution=body.resolution,
            ),
            now=clock.now(),
        )
    return view.to_dict()